import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Phát triển Android từ cơ bản đến nâng cao',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Cơ bản',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Hướng dẫn toàn diện về UI/UX',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Trung cấp',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Làm chủ các nguyên tắc cơ bản về mô hình hóa dữ liệu',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Cơ bản',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Hướng dẫn toàn diện về Docker và Kubernetes',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Trung cấp',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'React hiện đại với MUI & Redux',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Trung cấp',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Bootcamp Hacking Đạo đức từ con số 0 đến làm chủ',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Cơ bản',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Adobe Lightroom cho người mới bắt đầu: Chỉnh sửa ảnh toàn diện',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Cơ bản',
  },
]
